spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/data_hlc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      initialize: true
      
redis:
  host: localhost
  port: 6379
  pool:
   max-idle: 100
   min-idle: 1
   max-active: 1000
   max-wait: -1

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: org.spring.springboot.domain
  

 